### ISSUE TITLE
version for tampermankey

### ISSUE THREAD

**Issue by qzmtch** [glasket/pogext#1]
can you add a version for tampermonkey?

**Comment by glasket** [comment]
This is somewhat out of scope, but it is a minor change. I'll start including a separate script file in the releases that can be imported into things like TamperMonkey in the future.

Until I get another release out, you can paste/import the [pog.js](https://github.com/Glasket/pogext/blob/master/pog.js) file into TamperMonkey/GreaseMonkey/etc. and change the pog.src line (currently line 6) to point to a PogChamp image online like so:

`pog.src = chrome.runtime.getURL('images/128.png');`
will become
`pog.src = 'https://raw.githubusercontent.com/Glasket/pogext/master/images/128.png';`

This would point to the PogChamp image in this repo that I use.

**Comment by glasket** [comment]
> This is somewhat out of scope, but it is a minor change. I'll start including a separate script file in the releases that can be imported into things like TamperMonkey in the future.

Sorry for the sudden whiplash on this, but due to how I'm getting the extension to work site-wide it will have to be run as an extension. I'll pin a TamperMonkey release of the 1.1 version in the README, but for 1.2+ it requires browser APIs that aren't available via TamperMonkey-style extensions.

**Comment by glasket** [comment]
Actually, I'm going to open this back up for the time being due to the @grant permissions that TamperMonkey provides, specifically onurlchange.

I'll provide a gist to the 1.1 version as a TamperMonkey script, and I'll look into creating a 1.2 version in the next few days.

**Comment by qzmtch** [comment]
OK, understood

**Comment by glasket** [comment]
The 1.2 version for TamperMonkey has been added to the README, and is available [here](https://gist.github.com/Glasket/b9e7138024f902dce85e95d06c6bb8e8).
