### ISSUE TITLE
Emote search box breaks the replacement

### ISSUE THREAD

**Issue by Titanic4** [glasket/pogext#2]
Trying to use search box in emote picker causes the PogChamp to revert to one provided by Twitch. Once that happens the emote won't be replaced until you open different site on the same tab before coming back to Twitch, or when you open Twitch on different tab, in which case the extension will affect it.

Steps to repoduce: 
1. Open twitch.tv and open any active stream. I used https://www.twitch.tv/surrogategames as an example.
2. Open the emote picker. 
3. Try to use emote search box by using **any** query, for example: "😂". 
4. Clear the search box 

Chrome version:  88.0.4324.150 64-bit

**Comment by glasket** [comment]
I'll look into it, it sounds like searching causes the picker to load the emote containers differently than the normal behavior.

For now, refreshing will be enough to fix it when it breaks, navigating to another site and back shouldn't be necessary because it's the same behavior as a refresh.

**Comment by glasket** [comment]
Issue is resolved by https://github.com/Glasket/pogext/commit/c9a97890e4ef8a5d35c5cce97850053e0ef32ec1. Should be going live within the next week, depending on Web Store delays.
